version: "3.1"

volumes:
    db-data:

services:

    django:
      build: ./seller/django
      container_name: seller_django
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/application
      ports:
        - "8000:8000"
      depends_on:
        - mysql

    mysql:
      image: mysql:5.6
      container_name: seller_django-mysql
      working_dir: /application
      volumes:
        - db-data:/application
      environment:
        - MYSQL_ROOT_PASSWORD=docker_root
        - MYSQL_DATABASE=docker_django_db
        - MYSQL_USER=dbuser
        - MYSQL_PASSWORD=dbpw
      ports:
        - "8306:3306"