# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-09-14 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.CharField(blank=True, max_length=30, null=True)),
                ('summe', models.IntegerField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
