# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-09-14 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_math', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvseller',
            name='summe',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
